Move downloaded sources into an ignored subdirectory

diff --git a/Get b/Get
--- a/Get
+++ b/Get
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+cd build || ( echo "build/ not found. Are you running this in the right place?" && exit 5 ) || exit 5
+
 if [ -z "${2}" ]; then
 	echo "You forgot to give any arguments."
 	exit 255
